FROM python:3.9-slim

WORKDIR /app

# Копируем зависимости и устанавливаем пакеты
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем исходный код приложения
COPY frontend.py .

# Открываем порт 8501
EXPOSE 8501

# Запускаем Streamlit-приложение (CORS отключен для доступа к бэкенду)
CMD ["streamlit", "run", "frontend.py", "--server.port", "8501", "--server.enableCORS", "false"]
