FROM python:3.9-slim

WORKDIR /app

# Копируем зависимости и устанавливаем пакеты
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем исходный код и модель
COPY backend.py .
COPY best_xgb_model.pkl .

# Открываем порт 5001
EXPOSE 5001

# Запускаем приложение через uvicorn (без --reload)
CMD ["uvicorn", "backend:app", "--host", "0.0.0.0", "--port", "5001"]
